### ISSUE TITLE
Shows "99+" for all webpages

### ISSUE THREAD

**Issue by hsribei** [aido179/zwBlocker#1]
Hi! Thanks for the extension, I really enjoyed your post on Medium.

I'm taking it for a pin and so far I'm seeing the counter as "99+" regardless of the website I visit.

The selection notification works fine though.

**Comment by aido179** [comment]
Hmm, I have noticed that. I think it might be checking something non-text...will investigate. If you  are (or anybody else is)  interested, it's most likely something in [this](https://github.com/aido179/zwBlocker/blob/067c647b48112170dcd5309f55566e43840ed115/contentScript.js#L7) function.

Thanks for the feedback.

**Comment by aido179** [comment]
fixed in 84832590b960fc6fe4d083964b5aac875cba2593
